version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}                     
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql2
volumes:
  mysql-volume:
    driver: local